spring:
  application:
    name: stock.monitoring
  profiles:
    active: dev
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: -1
      use-key-prefix: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: ${REDIS_DB_INDEX}
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    virtual-host: ${RABBIT_MQ_VHOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DB_URL}:${MYSQL_DB_PORT}/${MYSQL_DB_SCHEMA}?autoReconnect=true&useSSL=false
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}

ranking.strategy: scoreRankingStrategy


