REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_DB_INDEX: 0

RABBIT_MQ_HOST: localhost
RABBIT_MQ_VHOST: /
RABBIT_MQ_PORT: 5672
RABBIT_MQ_USER: guest
RABBIT_MQ_PASSWORD: guest


MYSQL_DB_URL: localhost
MYSQL_DB_PORT: 3306
MYSQL_DB_USERNAME: root
MYSQL_DB_PASSWORD: ''
MYSQL_DB_SCHEMA: stock